{
 "title": "Data TEST STechnology",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temp Proceso Tanque 2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"DB-data\"",
     "measure": "xaxis",
     "rawQuery": "select time, measure_value::double as temp from \"DB-data\".\"sensor-data\" WHERE measure_name = 'temp' and \"device-id\" = 'gateway2'",
     "table": "\"sensor-data\""
    }
   ]
  },
  {
   "title": "Temp Proceso Tanque 1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"DB-data\"",
     "measure": "xaxis",
     "rawQuery": "select time, measure_value::double as temp from \"DB-data\".\"sensor-data\" WHERE measure_name = 'temp' and \"device-id\" = 'gateway1'",
     "table": "\"sensor-data\""
    }
   ]
  },
  {
   "title": "yaxis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "database": "\"DB-data\"",
     "measure": "xaxis",
     "rawQuery": "select time, measure_value::double as yaxis from \"DB-data\".\"sensor-data\" WHERE measure_name = 'yaxis' and \"device-id\" = 'gateway1'",
     "table": "\"sensor-data\""
    }
   ]
  },
  {
   "title": "xaxis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "database": "\"DB-data\"",
     "measure": "xaxis",
     "rawQuery": "select time, measure_value::double as xaxis from \"DB-data\".\"sensor-data\" WHERE measure_name = 'xaxis' and \"device-id\" = 'gateway1'",
     "table": "\"sensor-data\""
    }
   ]
  },
  {
   "title": "zaxis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "database": "\"DB-data\"",
     "measure": "xaxis",
     "rawQuery": "select time, measure_value::double as zaxis from \"DB-data\".\"sensor-data\" WHERE measure_name = 'zaxis' and \"device-id\" = 'gateway1'",
     "table": "\"sensor-data\""
    }
   ]
  },
  {
   "title": "Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "database": "\"DB-data\"",
     "measure": "xaxis",
     "rawQuery": "select time, measure_value::double as temp from \"DB-data\".\"sensor-data\" WHERE measure_name = 'temp' and \"device-id\" = 'gateway1'",
     "table": "\"sensor-data\""
    }
   ]
  }
 ]
}